
######################################
# Doctors Office Backend Helm Charts #
######################################

replicaCount: 3

image:
  repository: 850995557355.dkr.ecr.us-east-1.amazonaws.com/final/backend
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

securityContext:
  runAsUser: 1000
  runAsNonRoot: true
  readOnlyRootFilesystem: true

service:
  type: LoadBalancer
  port: 3000
  targetPort: 3000

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

roleBinding:
  ref: secret-phrase-access