apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-phrase-access-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: {{ include "backend.fullname" . }}-sa
  namespace: default
roleRef:
  kind: Role
  name: {{ .Values.roleBinding.ref }}
  apiGroup: rbac.authorization.k8s.io
